name: Bug report
description: Create a report to help improve this app
title: '[bug] '
labels: bug
body:
 - type: markdown
   attributes:
      value: |
        **Bug Report Protocol**

        Please perform the following checks before submitting:
        1. Verify this has not been reported previously.
        2. Check the [Known Issues](https://codeberg.org/brittytino/t_launcher/src/branch/main/docs/known-issues.md).
        3. Ensure you can reproduce this on the latest version.

        *Note: If this is a UX complaint rather than a crash/functional error, please use the Feature Request form which covers philosophy checks.*
 - type: textarea
   id: bug
   attributes:
     label: Describe the Bug
     description: What happened?
     placeholder: A clear and concise description of what the bug is.
   validations:
     required: true
 - type: textarea
   id: expected
   attributes:
     label: Expected Behavior
     description: What did you expect to happen instead?
   validations:
     required: false
 - type: textarea
   id: reproduce
   attributes:
     label: To Reproduce
     description: What steps are required to reproduce the bug?
     placeholder: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
   validations:
     required: false
 - type: textarea
   id: device
   attributes:
     label: Your Device
     description: |
       What device are you using? Adding this information helps to reproduce the bug.
       You can copy this from T Launcher > Settings > Meta > Report Bug.
   validations:
     required: false
